### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by edwintcloud** [dins-app/web-app#3]
- [x] Slide down animation for when additional options is clicked
- [ ] See More button after popular recipes that leads to Recipes page
- [ ] Recipes page (Screen 5 Zeplin)
  - [ ] Slide in from bottom 

Zeplin: [here](https://app.zeplin.io/project/5c885146174bdf196a2be157/dashboard)
